@startuml

boundary Frontend as fe order 10
control Backend as be order 20
control Lambda as l order 30

group Start of the game
    alt creating game
        fe -> be: new game
        be -> be: creates lobby
    else connecting to the existed game
        fe -> be: connect to the game
        be -> be: updates lobby
    end
    be --> fe:  show lobby

    fe -> be: start game

    be -> l: create lambda
    l -> l: create game
    l -> l: register socket
    l --> be: game info
    be --> fe:  game info
    fe -> fe:  register socket


    fe -> l: start:game
    l --> fe:  game:status
end

loop
    group Move Preparation
        group Bag can be shuffled more than once
            fe -> l: emit bag:shuffle
        end
        fe -> l: emit select:first:display

        loop for each display
            l --> fe : emit move:from:bag:to:display
        end
    end

    group Move
        fe -> l: move:from:display:to:pattern:line
        l --> fe:  game:status
    end

    group Move End
        loop
            l --> fe:  move:from:pattern:line:to:wall
        end
    end
end

group End of the Game
    l --> fe: add:horizontal:line:bonus
    l --> fe: add:vertical:line:bonus
    l --> fe: add:color:bonus
    l --> fe: game:over
    group if you are host
        fe -> be: game:results
    end
end

@enduml
